version: "3"

services:
  prepare_for_tfstate:
    image: hashicorp/terraform:1.8
    volumes:
      - ~/.aws:/root/.aws:ro
      - ./prepare_for_tfstate:/workdir
      - ./envs:/workdir/envs
    working_dir: "/workdir"

  hogehoge:
    image: hashicorp/terraform:1.8
    volumes:
      - ~/.aws:/root/.aws:ro
      - ./hogehoge:/workdir
      - ./envs:/workdir/envs
    working_dir: "/workdir"
    # env_file:
    #   - .env
    # entrypoint: ash
    # tty: true
    # environment:
    #   - AWS_ACCESS_KEY_ID
    #   - AWS_SECRET_ACCESS_KEY
    #   - AWS_SESSION_TOKEN
    #   - AWS_REGION
    #   - AWS_DEFAULT_REGION
    #   - AWS_PROFILE