version: "3"

services:
  lambda:
    # lambda関数のdockerイメージを作成してECRに登録するのにdockerコマンドが要る
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/.aws:/root/.aws:ro
      - ./lambda:/workdir
      - ./envs:/workdir/envs
      - /var/run/docker.sock:/var/run/docker.sock # dockerコマンドを動かすのに必要
    working_dir: "/workdir"

  prepare_for_tfstate:
    image: hashicorp/terraform:1.8
    volumes:
      - ~/.aws:/root/.aws:ro
      - ./prepare_for_tfstate:/workdir
      - ./envs:/workdir/envs
    working_dir: "/workdir"

  s3:
    image: hashicorp/terraform:1.8
    volumes:
      - ~/.aws:/root/.aws:ro
      - ./s3:/workdir
      - ./envs:/workdir/envs
    working_dir: "/workdir"
    # env_file:
    #   - .env
    # entrypoint: ash
    # tty: true
    # environment:
    #   - AWS_ACCESS_KEY_ID
    #   - AWS_SECRET_ACCESS_KEY
    #   - AWS_SESSION_TOKEN
    #   - AWS_REGION
    #   - AWS_DEFAULT_REGION
    #   - AWS_PROFILE