version: "3"

services:
  terraform:
    image: hashicorp/terraform:1.8
    volumes:
      - ~/.aws:/root/.aws:ro
      - ./:/workdir
    # env_file:
    #   - .env
    working_dir: "/workdir"
    # entrypoint: ash
    # tty: true
    # environment:
    #   - AWS_ACCESS_KEY_ID
    #   - AWS_SECRET_ACCESS_KEY
    #   - AWS_SESSION_TOKEN
    #   - AWS_REGION
    #   - AWS_DEFAULT_REGION
    #   - AWS_PROFILE