version: '3'
services:
    # localのdockerでlambda関数のdockerイメージを動かす場合に使う
    foo:
        container_name: foo
        image: foo
        build:
            context: .
            dockerfile: Dockerfile
        tty: true
        restart: always
        ports:
            - 9000:8080
